# Generated by Django 4.0.8 on 2023-07-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
        migrations.AddField(
            model_name='book',
            name='formats',
            field=models.CharField(blank=True, choices=[('PB', 'Paperback'), ('HC', 'Hardcover'), ('EB', 'Ebook'), ('AB', 'Audiobook')], default='PB', max_length=4),
        ),
        migrations.AddField(
            model_name='book',
            name='languages',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('pl', 'Polish'), ('ger', 'German')], default='en', max_length=4),
        ),
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
