# Generated by Django 4.0.8 on 2023-07-20 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_language_remove_book_languages_book_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='languages',
        ),
    ]
